"""empty message

Revision ID: 25a1e7abfc98
Revises: 4c40768458fd
Create Date: 2022-05-31 23:45:15.288901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a1e7abfc98'
down_revision = '4c40768458fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=105), autoincrement=False, nullable=True),
    sa.Column('interest_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('job_zone', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=733), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='interests_pkey')
    )
    # ### end Alembic commands ###
