"""empty message

Revision ID: 302bce7cc686
Revises: 65b3ffc87055
Create Date: 2022-05-30 13:44:07.753067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302bce7cc686'
down_revision = '65b3ffc87055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
