"""empty message

Revision ID: 306ba49679bc
Revises: 302bce7cc686
Create Date: 2022-05-30 13:48:30.818034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306ba49679bc'
down_revision = '302bce7cc686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
