"""empty message

Revision ID: 4c40768458fd
Revises: b69990546db0
Create Date: 2022-05-30 14:12:36.158630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c40768458fd'
down_revision = 'b69990546db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('faculty', sa.String(length=25), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('graduated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('courses', 'url',
               existing_type=sa.VARCHAR(length=102),
               nullable=True)
    op.alter_column('courses', 'is_paid',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('courses', 'num_subscribers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'avg_rating',
               existing_type=sa.NUMERIC(precision=7, scale=5),
               nullable=True)
    op.alter_column('courses', 'avg_rating_recent',
               existing_type=sa.NUMERIC(precision=7, scale=5),
               nullable=True)
    op.alter_column('courses', 'rating',
               existing_type=sa.NUMERIC(precision=7, scale=5),
               nullable=True)
    op.alter_column('courses', 'num_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'num_published_lectures',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'field',
               existing_type=sa.VARCHAR(length=22),
               nullable=True)
    op.alter_column('interests', 'title',
               existing_type=sa.VARCHAR(length=105),
               nullable=True)
    op.alter_column('interests', 'interest_code',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('interests', 'job_zone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interests', 'description',
               existing_type=sa.VARCHAR(length=733),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interests', 'description',
               existing_type=sa.VARCHAR(length=733),
               nullable=False)
    op.alter_column('interests', 'job_zone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interests', 'interest_code',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('interests', 'title',
               existing_type=sa.VARCHAR(length=105),
               nullable=False)
    op.alter_column('courses', 'field',
               existing_type=sa.VARCHAR(length=22),
               nullable=False)
    op.alter_column('courses', 'num_published_lectures',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'num_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'rating',
               existing_type=sa.NUMERIC(precision=7, scale=5),
               nullable=False)
    op.alter_column('courses', 'avg_rating_recent',
               existing_type=sa.NUMERIC(precision=7, scale=5),
               nullable=False)
    op.alter_column('courses', 'avg_rating',
               existing_type=sa.NUMERIC(precision=7, scale=5),
               nullable=False)
    op.alter_column('courses', 'num_subscribers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'is_paid',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('courses', 'url',
               existing_type=sa.VARCHAR(length=102),
               nullable=False)
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_table('users')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
