"""empty message

Revision ID: 5b2122a8915d
Revises: 867ac6231b12
Create Date: 2022-05-30 14:03:42.376049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2122a8915d'
down_revision = '867ac6231b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
