"""empty message

Revision ID: 65b3ffc87055
Revises: a9d3a932e6a8
Create Date: 2022-05-30 13:43:05.819879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b3ffc87055'
down_revision = 'a9d3a932e6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
