"""empty message

Revision ID: 7c6a7fe0e7ab
Revises: d1cfa1c8ea26
Create Date: 2022-07-02 16:28:42.415833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6a7fe0e7ab'
down_revision = 'd1cfa1c8ea26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interests', 'title',
               existing_type=sa.VARCHAR(length=105),
               nullable=True)
    op.alter_column('interests', 'interest_code',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('interests', 'job_zone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interests', 'description',
               existing_type=sa.VARCHAR(length=733),
               nullable=True)
    op.alter_column('interests', 'sector',
               existing_type=sa.VARCHAR(length=22),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interests', 'sector',
               existing_type=sa.VARCHAR(length=22),
               nullable=False)
    op.alter_column('interests', 'description',
               existing_type=sa.VARCHAR(length=733),
               nullable=False)
    op.alter_column('interests', 'job_zone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interests', 'interest_code',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('interests', 'title',
               existing_type=sa.VARCHAR(length=105),
               nullable=False)
    # ### end Alembic commands ###
