"""empty message

Revision ID: b69990546db0
Revises: 5b2122a8915d
Create Date: 2022-05-30 14:06:56.824137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69990546db0'
down_revision = '5b2122a8915d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
