"""empty message

Revision ID: d1cfa1c8ea26
Revises: 25a1e7abfc98
Create Date: 2022-05-31 23:51:53.000423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cfa1c8ea26'
down_revision = '25a1e7abfc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interests', 'title',
               existing_type=sa.VARCHAR(length=105),
               nullable=True)
    op.alter_column('interests', 'interest_code',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('interests', 'job_zone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interests', 'description',
               existing_type=sa.VARCHAR(length=733),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interests', 'description',
               existing_type=sa.VARCHAR(length=733),
               nullable=False)
    op.alter_column('interests', 'job_zone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interests', 'interest_code',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('interests', 'title',
               existing_type=sa.VARCHAR(length=105),
               nullable=False)
    # ### end Alembic commands ###
